# Make sure a NGINX proxy is running first
# Without SSL
#
# docker run -d -p 80:80 \
#   --name nginx-proxy-ssl \
#   -v /var/run/docker.sock:/tmp/docker.sock:ro \
#   jwilder/nginx-proxy:latest

# With SSL (using a private SSL enabled NGINX image)
#
# docker run -d -p 80:80 -p 443:443 \
#   --name nginx-proxy-ssl \
#   -v /var/run/docker.sock:/tmp/docker.sock:ro \
#   <yourprivate>/nginx-proxy-ssl:latest
#

mongo:
  image: mongo:latest
  restart: always
  command: mongod --storageEngine=wiredTiger

redoc:
  image: reactioncommerce/redoc:latest
  ports:
    - 80:80
  links:
    - mongo
  restart: always
  environment:
    ROOT_URL: "https://rocket.chat/docs"
    MONGO_URL: "mongodb://mongo:27017/redoc"
    VIRTUAL_HOST: "rocket.chat.docs"
